### ISSUE TITLE
GA not sending Completed Order as an event

### ISSUE THREAD

**Issue by gonegreen** [segmentio/analytics.js-integrations#134]
I may be wrong here but it doesn't appear that GA sends the "Completed Order" track as an event. It correctly sends the ecommerce purchase but fails to actually send a standard event which requires the addition of another track() call with another event such as "Completed Purchase". Is this intentional or am I missing something?

All my transactions track in GA and all events are there but that one.

**Comment by ndhoule** [comment]
This issue was moved to segment-integrations/analytics.js-integration-google-analytics#5
