### ISSUE TITLE
Add support for other SaaSquatch 'init' parameters

### ISSUE THREAD

**Issue by loganvolkers** [segmentio/analytics.js-integrations#141]
There are a few parameters missing for the SaaSquatch integration that are required to get things rolling.

The SaaSquatch integration already supports the custom traits of `accountId`, `referralImage` and `checksum`. We also need support for `mode` and `payment_provider_id`

 - TODO: Add support for the trait `payment_provider_id` in `identify`
 - TODO: Add support for the field `mode` in `init`

Ideally it would be handy if these parameters could be extensible. 

 - TODO: Add generic extensible support for something like `saasquatch.otherCustomTrait1`

I would be happy to contribute the patch, I just need some guidance on the best practices for custom traits.

**Comment by ndhoule** [comment]
This issue was moved to segment-integrations/analytics.js-integration-saasquatch#2
