### ISSUE TITLE
Quantcast: uid parameter doesn't actually get sent

### ISSUE THREAD

**Issue by dpolivy** [segmentio/analytics.js-integrations#171]
If the `user.id()` return value is not a string, then the Quantcast integration won't send the `uid` parameter with the tracking calls. This is because the Quantcast code itself requires option values to be strings, or else it won't serialize it.

I see a couple of possible opportunities to fix this, with the most likely solution coming in the analytics.js identify API to force whatever is passed as the userId into a string value. That way, it should always propagate as a string through to all integrations. However, this seems like a pretty core change and I'm not sure I'm comfortable making it myself.

Thoughts?

**Comment by ndhoule** [comment]
This issue was moved to segment-integrations/analytics.js-integration-quantcast#1
