### ISSUE TITLE
default page name to `document.title` in GA

### ISSUE THREAD

**Issue by DirtyAnalytics** [segmentio/analytics.js-integrations#194]
I'd like to default GA page title to the real document.title, then fall back to page name. [Right now we do the opposite](https://github.com/segmentio/analytics.js-integrations/blob/master/lib/google-analytics.js#L162).

The reason for this is that I like recommending people to use more generic page names like Blog or Docs, then they have a nice page event in event tracking tools and they can add the specifics like the actual blog post or docs page as props. 

That strategy is great for most tools, but the way we have GA setup it'll make the data less useful. 

@ianstormtaylor @reinpk @yields what do you think?

**Comment by f2prateek** [comment]
@DirtyAnalytics is this something we should still look into?

**Comment by DirtyAnalytics** [comment]
i dono maybe not no one has ever said anything it just seemed weird to me... maybe they like it! closing unless we hear requests about this :)

**Comment by f2prateek** [comment]
Thanks!
