### ISSUE TITLE
pass in config to sentry

### ISSUE THREAD

**Issue by ianstormtaylor** [segmentio/analytics.js-integrations#198]
Sentry allows for a series of configuration options, would be nice to support at least some of the more important ones.

**Comment by sperand-io** [comment]
FYI, +1 from another customer here @ndhoule @amillet89 @harrietgrace :)

https://segment.zendesk.com/agent/tickets/22659

**Comment by ndhoule** [comment]
This issue was moved to segment-integrations/analytics.js-integration-sentry#2
