### ISSUE TITLE
intercom: post-fix date traits with `_at`

### ISSUE THREAD

**Issue by ianstormtaylor** [segmentio/analytics.js-integrations#209]
Server-side we do this so that Intercom users can see nicely formatted dates, since Intercom doesn't recognize them automatically from the JSON sent. So we should change the client-side integration to do this as well. 

We'll need to make it backwards compatible with the old traits as well.

@calvinfo

**Comment by ndhoule** [comment]
This issue was moved to segment-integrations/analytics.js-integration-intercom#2
