### ISSUE TITLE
support GA content groups

### ISSUE THREAD

**Issue by DirtyAnalytics** [segmentio/analytics.js-integrations#210]
Here's the [GA docs](https://support.google.com/analytics/answer/2853546?hl=en#code).

When these are set directly through GA the code looks like this:

```javascript
ga('create', 'UA-XXXXXXXX-Y', 'example.com');
ga('set', 'contentGroup5', 'Docs');
ga('send', 'pageview');
```

And here's how I think it should work in Segment...

When people call this: 

```javascript
analytics.page({
  contentGrouping: 1,
  contentGroup: 'Men'
});
```

Becomes:

```javascript
analytics.js: ga('set', 'contentGroup1', 'Men');
```

There are 5 content groupings slots available in GA, grouping is the very top level category, examples would be: 

- clothing
- marketing
- docs
- app

Then there are content groups which the user defines as a string and for that reason there can be as many as they want, groups always fit under a content grouping, here are some examples that would fit in the groupings above: 

- shirts
- case studies
- integrations
- settings

Let me know if this makes sense @ianstormtaylor @yields @calvinfo @lancejpollard 

Also - let's only worry about supporting the GA universal tracking method.

**Comment by ndhoule** [comment]
This issue was moved to segment-integrations/analytics.js-integration-google-analytics#4
