### ISSUE TITLE
Facebook Custom Audience

### ISSUE THREAD

**Issue by cyberwombat** [segmentio/analytics.js-integrations#239]
Gonna work on this a bit - is this being addressed by anyone? Suggestions?

Here's the pixel tag https://gist.github.com/cyberwombat/40b8f345082254a2b89c

**Comment by ndhoule** [comment]
Facebook Custom Audiences is supported through Segment now (docs are [here](https://segment.com/docs/integrations/facebook-custom-audiences/)), closing.
