### ISSUE TITLE
curebit: add custom script location

### ISSUE THREAD

**Issue by calvinfo** [segmentio/analytics.js-integrations#246]
curebit is changing their API to have a custom script location. It should be solved by having a setting, and then loading the script from that setting.

new scripts will look like this and be served per client:

```
http://d2jjzw81hqbuqv.cloudfront.net/integration/clients/bonobos.min.js
```

**Comment by ndhoule** [comment]
This issue was moved to segment-integrations/analytics.js-integration-curebit#1
