### ISSUE TITLE
kissmetrics doesn't fire kissmetrics default pageview events

### ISSUE THREAD

**Issue by reinpk** [segmentio/analytics.js-integrations#250]
https://github.com/segmentio/analytics.js-integrations/blob/master/lib/kissmetrics/index.js#L65

should call `.page()` rather than `.trackPage()`, otherwise the default pageview doesn't get generated at all (here I have to manually trigger it from the console on our own site):
https://cloudup.com/cX6Q4dbQ4U2

our kissmetrics account shows no default pageviews either, and a helpful user pointed out that they're not seeing them either

**Comment by ndhoule** [comment]
This issue was moved to segment-integrations/analytics.js-integration-kissmetrics#1
