### ISSUE TITLE
Allow "Group" prefix to be configurable

### ISSUE THREAD

**Issue by summerville** [segmentio/analytics.js-integrations#350]
Services that don't natively support "groups" (e.g. Customer.io) get the group traits appended the user traits when the `group()` function is used. Each of the group traits are copied over and the keys are prefixed with the string "Group ".

It would be awesome to configure the automatic prefix. For us, we would use "account_" or something similar b/c we'd rather see `"account_id"` instead of `"Group id"` in the different analytics tools we use.

**Comment by ndhoule** [comment]
This issue was moved to segmentio/analytics.js#469
