### ISSUE TITLE
Getting tests to pass with `make test-sauce`

### ISSUE THREAD

**Issue by lancejpollard** [segmentio/analytics.js-integrations#357]
@yields getting closer to figuring out the `make test-sauce` issue. I think the reason it is freezing is because some of the scripts don't load, maybe because they only load if they are registered with the integration provider against a certain domain, like localhost.

```
$ DEBUG=duo-test:saucelabs make test-sauce browser=chrome
```

This is an issue though because we're dynamically generating a domain name through localtunnel. Not sure yet how we're going to resolve this haha, any ideas?

![screen shot 2014-07-24 at 4 54 27 pm](https://cloud.githubusercontent.com/assets/28718/3696415/1d9f1fa6-138e-11e4-9c38-baefd97221a2.png)

We somehow need to have a specific domain that we can use that never changes, and then register with those services a domain. Or maybe they will accept `*.localtunnel` as a domain?

![screen shot 2014-07-24 at 4 58 42 pm](https://cloud.githubusercontent.com/assets/28718/3696429/7954523a-138e-11e4-8036-adeebdb19fe4.png)

hmm with ClickTale we would have to have a different subscription for that.

/cc @reinpk @ianstormtaylor

**Comment by ndhoule** [comment]
Moved the issue of testing via Sauce Labs to Trello, will tackle down the line.
