### ISSUE TITLE
Optimizely integration replaying all experiments. Should only replay active experiments?

### ISSUE THREAD

**Issue by jfeldstein** [segmentio/analytics.js-integrations#37]
window.Optimizely.data.experiments contains data on [all experiments in the project](https://www.optimizely.com/docs/api#experiments). 

As is, the integration is copying [all experiments into the user's attributes](https://github.com/segmentio/analytics.js-integrations/blob/master/lib/optimizely.js#L101), which makes it hard/impossible to query for events that were triggered by users who are seeing / have seen a given experiment or variation. 

Would it not be better to only report experiments included in window.Optimizely.data.activeExperiments?

**Comment by ndhoule** [comment]
This issue was moved to segment-integrations/analytics.js-integration-optimizely#1
