### ISSUE TITLE
saasquatch: accountId and referralImage are wrong

### ISSUE THREAD

**Issue by ianstormtaylor** [segmentio/analytics.js-integrations#383]
- `accountId` should map to our `groupId` I think.
- `referralImage` should be a setting in the interface I think.

Here are the docs for the Saasquatch `init` method: http://docs.referralsaasquatch.com/squatchjs#init

**Comment by ndhoule** [comment]
This issue was moved to segment-integrations/analytics.js-integration-saasquatch#1
