### ISSUE TITLE
intercom monthly spend

### ISSUE THREAD

**Issue by sperand-io** [segmentio/analytics.js-integrations#422]
Hey y'all. Great job on the server-side intercom fixes!

Noticed that over there you're using a `monthlySpend` trait to populate revenue -- can we add that on client side tracking as well so that we have parity before adding that to docs?

cc/ @amillet89 @harrietgrace @DirtyAnalytics

**Comment by ndhoule** [comment]
This issue was moved to segment-integrations/analytics.js-integration-intercom#1
