### ISSUE TITLE
GA : Ability to set the path in the track() method.

### ISSUE THREAD

**Issue by TimmyCarbone** [segmentio/analytics.js-integrations#442]
Currently, we can set the ```path``` property in the ```page()``` method and it sets GA's ```pagePath``` property. 

It would be good for consistency to be able to set GA's ```pagePath``` in the ```track()``` method too.
We can set the ```path``` property but it won't affect GA's ```pagePath```.

To summarize, the virtual path doesn't work on GA events. Currently, events and pageviews can't be associated through the ```path```.

Should be something around there : 
https://github.com/segmentio/analytics.js-integrations/blob/master/lib/google-analytics/index.js#L207

with a property like this : 
https://github.com/segmentio/analytics.js-integrations/blob/master/lib/google-analytics/index.js#L173

**Comment by ndhoule** [comment]
This issue was moved to segment-integrations/analytics.js-integration-google-analytics#3
