### ISSUE TITLE
Update Keen API to 3.1.0 ?

### ISSUE THREAD

**Issue by QuentinFchx** [segmentio/analytics.js-integrations#466]
3.1.0 was just release ! https://github.com/keen/keen-js/releases/tag/v3.1.0

**Comment by d4rky-pl** [comment]
Latest version is 3.2, it would be really nice if it was supported OOTB.

**Comment by ndhoule** [comment]
Moving this over to https://github.com/segment-integrations/analytics.js-integration-keen-io/issues/1
