### ISSUE TITLE
hubspot: `identify` not usable dynamically

### ISSUE THREAD

**Issue by trisrael** [segmentio/analytics.js-integrations#489]
Noticed that using `analytics.identify` does not start any XHR (or other requests) against hubspot apis/endpoints.

Found that the integration is using `_hsq.push` which is not supported using the [javascript api](http://developers.hubspot.com/docs/methods/enterprise_events/javascript_api). Manually reloading the script via `new analytics.Integrations.HubSpot({portalId: PORTAL_ID}).load()` caused some call to be made to a Hubspot API but only the last item pushed onto the 'queue'.

Maybe segment.io could have this as proxy integration instead since they are storing the Hubspot api-key for server side calls to the Hubspot API.

**Comment by ndhoule** [comment]
Hey @trisrael, the link you referenced shows `_hsq.push` as part of the example call. I'm closing this for now, but feel free to re-open if there's something we're missing.

**Comment by nathan-appere** [comment]
We do have this issue, and the Hubspot documentation states: `Simply calling the identify method will not push the identities to HubSpot.` Are all segment integrations tested end to end ? Because it is unlikely this works at all.
