### ISSUE TITLE
GA Enhanced Ecommerce - Viewed Product vs Viewed Product Detail

### ISSUE THREAD

**Issue by sperand-io** [segmentio/analytics.js-integrations#505]
just noticed this incongruity in the enhanced ecommerce integration from our ecommerce API spec:

In the integration, the `Viewed Product` event triggers the `ec:addImpression` method, which is actually meant for product impressions (like seeing a product in a list of products) whereas the `Viewed Product Details` event is calling the GA method for actually viewing a product detail page (and which is not listed as a standard ecommerce .

Since other integrations conform to the API, the `Viewed Product` event to them means "visited product detail page" whereas in GA EE it means "Saw Product in a List of Other Products". Not good!

https://developers.google.com/analytics/devguides/collection/analyticsjs/enhanced-ecommerce#product-impression

vs.

https://developers.google.com/analytics/devguides/collection/analyticsjs/enhanced-ecommerce#product-detail-view

https://github.com/segmentio/analytics.js-integrations/blob/master/lib/google-analytics/index.js#L82-L84

Thinking we should remap these events as follows (feedback welcome) - 

product impression (currently `Viewed Product`) => "Viewed Product Listing"
product view (currently `Viewed Product Details`) => "Viewed Product"

thoughts?  @DirtyAnalytics @amillet89 @yields @harrietgrace @ndhoule

**Comment by stevenmiller888** [comment]
Relevant tickets:

1) https://segment.zendesk.com/agent/tickets/19418

2) https://segment.zendesk.com/agent/tickets/24063
