### ISSUE TITLE
GA Enhanced Ecommerce - common event category and actions

### ISSUE THREAD

**Issue by sperand-io** [segmentio/analytics.js-integrations#508]
Due to this method here: https://github.com/segmentio/analytics.js-integrations/blob/master/lib/google-analytics/index.js#L519-L523

Every enhanced ecommerce event has the same category and action ('EnhancedEcommerce' and 'Push', respectively.)

![](https://cloudup.com/cOwjHXEnW7Z+)

![](https://cloudup.com/cNiSIMfAxJr+)

this can cause some confusion: https://segment.zendesk.com/agent/tickets/23190

Should we use track.event() to use the event name for the action??

@DirtyAnalytics @amillet89

**Comment by DirtyAnalytics** [comment]
@sperand-io I think yes unless there's some reason not to

**Comment by sperand-io** [comment]
closed by #542
