### ISSUE TITLE
GA: add custom dimensions mapping in `.page()` calls

### ISSUE THREAD

**Issue by lambtron** [segmentio/analytics.js-integrations#516]
How we do it in `.track()` currently:
https://github.com/segmentio/analytics.js-integrations/blob/master/lib/google-analytics/index.js#L216-L217

Can be easily done in `.page()`.

Use case:
https://segment.zendesk.com/agent/tickets/23714

Thoughts?

/cc @amillet89

**Comment by sperand-io** [comment]
https://github.com/segmentio/analytics.js-integrations/blob/master/lib/google-analytics/index.js#L186-L188
