### ISSUE TITLE
Master is broken

### ISSUE THREAD

**Issue by yagnik** [segmentio/analytics.js-integrations#527]
@amillet89 would you mind running master on ci again, it seems google analytics integration is broken. 
I expect this build to fail when retried: https://circleci.com/gh/segmentio/analytics.js-integrations/225

**Comment by yagnik** [comment]
cc @drdee

**Comment by harrietgrace** [comment]
Hi @yagnik, thanks for getting in touch! I'm looking into this - will let you know when it's fixed :)

**Comment by yagnik** [comment]
hey @harrietgrace , I started looking at it too please let me know if I can help to resolve the issue. I wanted to make sure it's not just my branch that's failing.

**Comment by harrietgrace** [comment]
Definitely not just your branch :) We've got a fix organised, I'll ping you again once it's available!

**Comment by yagnik** [comment]
Looks like your latest changes did magic! thanks @harrietgrace. Closing this.

**Comment by harrietgrace** [comment]
No worries, @yields did the magic! Thanks for bringing it to our attention.
