### ISSUE TITLE
Add role property to satismeter and set traits to match spec

### ISSUE THREAD

**Issue by wcjohnson11** [segmentio/analytics.js-integrations#566]
[Noodle wants](https://segment.zendesk.com/agent/tickets/26290) Satismeter updated to pass a `role` property and wants to know how to pass through `signUpDate` which is currently from [user().created()](https://github.com/segmentio/analytics.js-integrations/blob/master/lib/satismeter/index.js#L61-L63) but our spec shows as [createdAt](https://segment.com/docs/spec/identify/#traits).

**Comment by sperand-io** [comment]
@wcjohnson11, can you give some more clear direction on what the proposed changes are here? thanks so much!
