### ISSUE TITLE
Satismeter role property and signUpDate

### ISSUE THREAD

**Issue by wcjohnson11** [segmentio/analytics.js-integrations#574]
[Noodle wants](https://segment.zendesk.com/agent/tickets/26290) Satismeter updated to pass a `role` property and wants to know how to pass through `signUpDate` which is currently from [user().created()](https://github.com/segmentio/analytics.js-integrations/blob/master/lib/satismeter/index.js#L61-L63) but our spec shows as [createdAt](https://segment.com/docs/spec/identify/#traits).

**Comment by ndhoule** [comment]
This issue was moved to segment-integrations/analytics.js-integration-satismeter#1
