### ISSUE TITLE
Adding Keen.io integration makes using keen's scoped keys impossible to use

### ISSUE THREAD

**Issue by d4rky-pl** [segmentio/analytics.js-integrations#591]
When we add Keen.io integration to Segment it forces us to provide read key in admin panel rather than anywhere in the code. This makes it impossible to use Keen's scoped keys as they are generated and can be unique for example per app user.

**Comment by ndhoule** [comment]
This issue was moved to segment-integrations/analytics.js-integration-keen-io#2
