### ISSUE TITLE
Old keen.js integration

### ISSUE THREAD

**Issue by d4rky-pl** [segmentio/analytics.js-integrations#592]
Analytics.js uses prehistoric version of keen.js that was released almost a year ago. The latest version as of writing this is 3.2.4 whereas analytics still use 3.0.8 that doesn't support new visualisation apis amongst other things.

**Comment by sperand-io** [comment]
Thanks @d4rky-pl — will get this updated in short order. cheers!

**Comment by d4rky-pl** [comment]
@sperand-io it might be a good idea to allow people to choose the library version in admin panel, otherwise switch between 3.0.8 to 3.2.4 may be painful for some people (some APIs have changed and I'm not sure if they're backwards compatible)

**Comment by dustinlarimer** [comment]
@d4rky-pl @sperand-io tracking functionality hasn't changed between those versions, though we've replaced a lot of internal request handling methods to tighten things up. We also added a `Keen.noConflict()` method to help avoid version collisions where possible. I would be happy to sync up on this and help! dustin@keen.io

**Comment by ndhoule** [comment]
This issue was moved to segment-integrations/analytics.js-integration-keen-io#1
