### ISSUE TITLE
Add Source Code of Pardot Integration to Repo

### ISSUE THREAD

**Issue by kevinthompson** [segmentio/analytics.js-integrations#614]
The Pardot integration is available in the Segment.io dashboard, but the source is not available here. I'm trying to resolve an issue with this integration, and I'd like to be able to contribute a potential solution, but it doesn't look like the source is available anywhere.

**Comment by f2prateek** [comment]
You are correct, the Pardot integration is closed source. I could send you a gist with the integration code, could you write in to friends@segment.com and explain your issue?

**Comment by kevinthompson** [comment]
Ah I see. I already have an ongoing dialog with support, but the gist of it is that because Pardot loads it's own analytics file when the primary script is loaded, there is no way to programmatically pass in a campaign ID before the default campaign ID is used.

I've managed to get it working with a pretty nasty hack that I'd rather not deploy to production:
``` js
analytics.load("...");
var start = new Date();
var loading = setInterval(function(){
  var loaded  = !!window.analytics._integration && !!window.analytics._integrations.Pardot
  var expired = new Date() - start >= 5000;
  if (loaded) window.analytics._integrations.Pardot.options.piCId = "...";
  if (loaded || expired) {
    clearInterval(loading);
    window.analytics.page();
  }
}, 10);
```

The documentation on both the Segment site and the Pardot site recommend using a url parameter to define the campaign ID, but that is not an option in my implementation. If there were a way to programmatically override the campaign id (`piCId`) option before the Pardot integration is initialized, that would solve my problem.

**Comment by kevinthompson** [comment]
I'll admit that I'm relatively new to using Segment.io, so I spent a bit of time in the docs today, and my initial hope was that in using the `analytics.page` method I'd be able to pass custom options for an integration. For example:

``` js
analytics.page({}, {
  integrations: {
    "All": true,
    "Pardot": {
      "piCId": "12345"
    }
  }
});
```

In the above example, the value provided is truthy so the integration is included, but the provided object would be merged into the options for that integration on this page.

**Comment by f2prateek** [comment]
Yup, I think it makes sense for us to add that to the integration so that it looks up a custom campaign ID, and falls back to the default one if a custom one is not defined.

**Comment by kevinthompson** [comment]
We've gotten off track with this issue so I'm going to close it. I've created a new related issue here: https://github.com/segmentio/analytics.js/issues/453
